mdoutput/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>MostRecentProjectPaymentDate__c</fullName>
        <description>Date of most recent payment to any project.  Null if no payments.</description>
        <label>Most Recent Project Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TotalProjectPayments__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Sum of all Project payments (across all projects)</description>
        <label>Total Project Payments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

mdoutput/objects/Payment__c.object
<CustomObject>
    <description>Join a payment to one Project and one Contact.
Both a Project and a Contact are required for a payment record.</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>Pmt-{000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AmountPaid__c</fullName>
        <description>Amount of payment</description>
        <label>Amount Paid</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contact that made this payment</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DatePaid__c</fullName>
        <description>Date this payment was made.</description>
        <label>Date Paid</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Project this payment is against.</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdoutput/objects/Project__c.object
<CustomObject>
    <description>Track Project information.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ContactSelector.cls
/**
 * Service class to hold all soql operations for Contact.
 */
public class ContactSelector {

    /**
     * public class representing a Contact object.  Additonal fields are provided
     * for calciulated info.
     */
    public class ContactInfo {
        public Contact contact {get; private set;}
        public Decimal calculatedTotalProjectPayments {get; private set;}
        public Date calculatedMostRecentProjectPaymentDate {get; private set;}

        public ContactInfo(Id ContactId,
                           Decimal totalPaid,
                           Date mostRecentPaymentDate) {
            this.contact = new Contact(Id = contactId);
            this.calculatedTotalProjectPayments = totalPaid;
            this.calculatedMostRecentProjectPaymentDate = mostRecentPaymentDate;
        }
    }

    /**
     * Return a list of Contacts (ContactInfo) with the total sum of payments and
     * most recent payment date for each contact.
     * @param projectIDs - List of specific projects to query
     * @result - Map of Contact IDs and ContactInfo objects for each contact found in contactIDs.
     *           NOTE: If a ContactID was supplied but that contact presently has no payments, then that contact
     *                 will NOT be returned in this map.
     */
    public static Map<Id, ContactInfo> getContactsByIdWithAggInfo(Set<Id> contactIDs) {
        AggregateResult[] getContactsByIdWithAggInfo = [SELECT Contact__c contactId,
                                                        sum(amountPaid__c) totalPaid,
                                                        max(datePaid__c) latestPaidDate
                                                        FROM Payment__c
                                                        GROUP BY Contact__c];

        Map<Id, ContactInfo> result = new Map<Id, ContactInfo>();
        for (AggregateResult ar : getContactsByIdWithAggInfo) {
            result.put( (Id)ar.get('contactId'),
                        new ContactInfo( (Id)ar.get('contactId'),
                                         (Decimal)ar.get('totalPaid'),
                                         (Date)ar.get('latestPaidDate')));
        }

        return result;
    }

    /**
     * Return all Contacts that have Payment__c records along with a
     * subselect of Payment records.
     */
    public static Contact[] getContactsWithPaymentInfo() {
        return [SELECT Name,
                MostRecentProjectPaymentDate__c,
                TotalProjectPayments__c,
                (Select Name,
                 AmountPaid__c,
                 DatePaid__c,
                 Project__r.Name
                 From Payments__r
                 Order By DatePaid__c DESC, CreatedDate DESC)
                FROM Contact
                WHERE Id IN (Select Contact__c From Payment__c)
                ORDER BY Name ASC];

    }

}