mdoutput/objects/Payment__c.object
<CustomObject>
    <description>Join a payment to one Project and one Contact.
Both a Project and a Contact are required for a payment record.</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>Pmt-{000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AmountPaid__c</fullName>
        <description>Amount of payment</description>
        <label>Amount Paid</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Project this payment is against.</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdoutput/objects/Project__c.object
<CustomObject>
    <description>Track Project information.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdoutput/classes/ProjectSelector.cls
/**
 * Service class to hold all soql operations for Project__c
 */
public class ProjectSelector {
    private ProjectSelector() {
    }

    /**
     * public class representing a Project__c object.  Additonal fields are provided
     * for calciulated info.
     */
    public class ProjectInfo {
        public Project__c project {get; private set;}
        public Decimal calculatedTotalPaid {get; private set;}

        public ProjectInfo(Id projectId,
                           Decimal totalPaid) {
            this.project = new Project__c(Id = projectId);
            this.calculatedTotalPaid = totalPaid;
        }
    }

    /**
     * Return a list of Projects (ProjectInfo) with the total sum of payments for each project.
     * @param projectIDs - List of specific projects to query
     * @result - Map of Project IDs and ProjectInfo objects for each project found in projectIDs.
     *           NOTE: If a projectID was supplied but that project presently has no payments, then that project
     *                 will NOT be returned in this map.
     */
    public static Map<Id, ProjectInfo> getProjectsByIdWithAggPayments(Set<Id> projectIDs) {
        AggregateResult[] ProjectsWithAggPayments = [SELECT Project__c projectId,
                                                     sum(amountPaid__c) totalPaid
                                                     FROM Payment__c
                                                     WHERE Project__c IN :projectIDs
                                                     GROUP BY Project__c];

        Map<Id, ProjectInfo> result = new Map<Id, ProjectInfo>();
        for (AggregateResult ar : ProjectsWithAggPayments) {
            result.put( (Id)ar.get('projectId'), new ProjectInfo( (Id)ar.get('projectId'), (Decimal)ar.get('totalPaid')));
        }

        return result;
    }

}