mdoutput/objects/Payment__c.object
<CustomObject>
    <description>Join a payment to one Project and one Contact.
Both a Project and a Contact are required for a payment record.</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>Pmt-{000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AmountPaid__c</fullName>
        <description>Amount of payment</description>
        <label>Amount Paid</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contact that made this payment</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DatePaid__c</fullName>
        <description>Date this payment was made.</description>
        <label>Date Paid</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Project this payment is against.</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdoutput/objects/Project__c.object
<CustomObject>
    <description>Track Project information.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdoutput/classes/ContactPaymentsManagerController_test.cls
@istest
public with sharing class ContactPaymentsManagerController_test {

    @testSetup
    static void testSetup() {
        // Set up infrastructure
        // Two Projects and two Contacts
        // contact1 has two payents.  contact2 has zero payments.
        Project__c project1 = new Project__c(Name = 'Project1'),
                   project2 = new Project__c(Name = 'Project2');
        insert new Project__c[] {project1, project2};
        Contact contact1 = new Contact(LastName = 'Contact1'),
                contact2 = new Contact(LastName = 'Contact2');
        insert new Contact[] {contact1, contact2};
        Date td = System.today();
        Payment__c pmt_P1C1 = new Payment__c(AmountPaid__c=1, DatePaid__c=td.addDays(-1), Project__c=project1.Id, Contact__c=contact1.Id),
                pmt_P2C1 = new Payment__c(AmountPaid__c=3, DatePaid__c=td.addDays(-3), Project__c=project2.Id, Contact__c=contact1.Id);
        insert new Payment__c[] {pmt_P1C1, pmt_P2C1};
    }

    @istest
    public static void getContactsWithPayments_test() {
        Test.startTest();
        Contact[] contactsResult = ContactsPaymentsManagerController.getContactsWithPayments();
        Test.stopTest();

        system.assertEquals(1, contactsResult.size());
        system.assertEquals('Contact1', contactsResult[0].Name);
        system.assertEquals(2, contactsResult[0].Payments__r.size());

    }

    @istest
    public static void deletePayment_test() {
        Payment__c payment1 = [SELECT Id FROM Payment__c LIMIT 1];

        Test.startTest();
        ContactsPaymentsManagerController.deletePayment(payment1.Id);
        Test.stopTest();
        
        Integer numberOfPayments = [SELECT count() FROM Payment__c];
        system.assertEquals(1, numberOfPayments);

    }
}