mdoutput/objects/Payment__c.object
<CustomObject>
    <description>Join a payment to one Project and one Contact.
Both a Project and a Contact are required for a payment record.</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>Pmt-{000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Project this payment is against.</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdoutput/objects/Project__c.object
<CustomObject>
    <description>Track Project information.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Payments.cls
public class Payments {
    public Payments() {}

    /**
     * Trigger handler for Payment__c objects.
     * Assumes Trigger context.
     */
    public static void handleTrigger() {

        // After payments are written to the database, need to update Project__c and Contact objects
        // with the correct payment roll-up information.
        if (trigger.isAfter) {
            new Projects().updateProjectPaymentInfo(trigger.old, trigger.new);
            new Contacts().updateContactPaymentInfo(trigger.old, trigger.new);
        }
    }

}